apiVersion: v1
kind: Service
metadata:
  name: counter-np
spec:
  type: NodePort
  ports:
    - port: 2222
      protocol: TCP
      targetPort: 3000 
      # ghcr.io/subicura/counter:latest 에서 접근을 3000번 포트로 하라고 했으니,
      # targetPort를 3000으로 수정해주면 port값은 뭐가 되던 상관이 없다.
      nodePort: 31000
  selector:
    app: counter
    tier: app