apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: counter
      tier: db
  template:
    metadata:
      labels:
        app: counter
        tier: db
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - protocol: TCP
              containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: counter
    tier: db

# 서비스가 두개이면, 먼저 생성된 서비스만 접속이 되는 것으로 확인됨
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis2
# spec:
#   ports:
#     - port: 6380
#       protocol: TCP
#   selector:
#     app: counter
#     tier: db