version: "3"
services:
  wordpress:
    image: wordpress:5.5.3-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: 1234
    ports:
      - "30000:80"
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234