apiVersion: v1
kind: Pod
metadata:
  name: echo2
  labels:
    app: echo
spec:
  containers:
    - name: app2
      image: ghcr.io/subicura/echo:v1
      livenessProbe:
        httpGet:
          path: /not/exist # 존재하지 않는 path
          port: 8080 # 존재하지 않는 포트
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1