apiVersion: v1
kind: Service
metadata:
  name: mysql # 이 name이 wp-config.php에서 DB_HOST 가 된다.!!
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306