# 동적볼륨할당 -> 으로 하니깐 안됨 pending 뜲 pvc 한번 생기면 지우기 골치아파진다...
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
#   labels:
#     pvc: mysql
# spec:
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/tmp/mysql-pv"
#   resources:
#     requests:
#       storage: 500Mi

# 두 단계(pv, pvc)로 진행
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pv: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql2"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    pvc: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      pv: mysql # binding할 pv를 생성된 pv중에서 label로 선택함
# ---
