apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydisk
spec:
  accessModes:
    - ReadWriteOnce
  resourcess:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: terrypath
          mountPath: /data/shared
  volumes:
    - name: terrypath
      persistentVolumeClaim:
        claimName: mydisk