FROM	alpine:3.12
EXPOSE	80 443 22

RUN		apk update
RUN 	apk add --no-cache nginx \
				openssl \
				openssh

# COPY	default.conf /etc/nginx/http.d/default.conf


COPY	prevent_exit.sh /prevent_exit.sh
COPY	./default.conf /etc/nginx/conf.d/default.conf
RUN		mkdir -p /run/nginx
# CMD		/usr/sbin/nginx 둘다 안되네
# ENTRYPOINT		/usr/sbin/nginx 둘다 안되네
CMD		/prevent_exit.sh