apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx	# deployment 이름
  labels:
    app: nginx
spec:
  replicas: 1	# pod 를 몇 개 띄울지
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ft_nginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 20

