FROM	alpine:3.12
EXPOSE	5000

RUN		apk update
RUN 	apk add php \
				php-fpm php-mbstring php-json php-session php-mysqli php-session
RUN		apk add nginx

RUN	wget -O /tmp/phpmyadmin.tar.gz https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
RUN tar -xzvf /tmp/phpmyadmin.tar.gz -C /tmp
RUN rm -rf /tmp/phpmyadmin.tar.gz
RUN mv /tmp/php* /tmp/phpmyadmin
RUN mv /tmp/phpmyadmin/config.sample.inc.php /tmp/phpmyadmin/config.inc.php

# config.inc.php 파일 수정
RUN sed -i '/AllowNoPassword/ s/false/true/g' /tmp/phpmyadmin/config.inc.php
RUN sed -i '/host/ s/localhost/mysql/g' /tmp/phpmyadmin/config.inc.php
# RUN sed -i '/blowfish_secret/ s/ /whatareyoudoinglgl1234546560093563049dfklsgdl;fgdsfgddg/g' /tmp/phpmyadmin/config.inc.php
RUN echo "\$cfg['TempDir'] = '/tmp';" >> /tmp/phpmyadmin/config.inc.php

COPY	default.conf /etc/nginx/conf.d/default.conf

COPY	prevent_exit.sh /prevent_exit.sh
RUN		mkdir -p /run/nginx
RUN		mkdir -p /tmp/phpmyadmin/tmp
# nginx로 phpmyadmin을 열려면 nginx, php-fpm7 을 실행시켜줘야함
CMD		/prevent_exit.sh

## nginx가 아닌 방법으로 port:5000 에 연결하는 방법
# CMD		php -S 0.0.0.0:5000 -t /tmp/phpmyadmin/
# /prevent_exit.sh 은php -S 0.0.0.0:5000 을 실행시키지못함
