apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: ft_phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 2
      
      ## 나는 이 부분을 Dockerfile에서 sed 명령어로 config.inc.php를 수정해주었음.
      #     volumeMounts:
      #       - name: phpmyadmin-config
      #         subPath: config.inc.php
      #         mountPath: /etc/phpmyadmin/config.inc.php
      #         readOnly: true
      # volumes:
      #   - name: phpmyadmin-config
      #     configMap:
      #       name: phpmyadmin
