apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports: 
    - port: 5432
      protocol: TCP
  selector:
    name: postgres


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
  labels:
    name: deploy-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels: 
        name : postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"