apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    pvc: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  selector:
    matchLabels:
      pv: influxdb # binding할 pv를 생성된 pv중에서 label로 선택함
