apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared # 접근 가능한 클러스터 ip가 minikube ip 하나 이기때문에, 하나로 고정시켜야함
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - port: 5050
      name: wordpress
      targetPort: 5050