apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - port: 21
      name: ftps-command
    - port: 20000
      name: ftps-pasv1
    - port: 20001
      name: ftps-pasv2
    - port: 20002
      name: ftps-pasv3
    - port: 20003
      name: ftps-pasv4
